import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../../theme/colors';
import { BEIJING_TRIP_MOCK } from '../../data/beijingHomeMock';

export default function CurrentTripCard({ elderlyMode, onPress }: { elderlyMode: boolean; onPress: () => void }) {
  const scale = elderlyMode ? 1.12 : 1;
  return <Pressable onPress={onPress} style={({ pressed }) => [styles.card, pressed && styles.pressed]}>
    <View style={styles.header}><View><Text style={[styles.kicker, { fontSize: 10 * scale }]}>{BEIJING_TRIP_MOCK.title}</Text><Text style={[styles.day, { fontSize: 24 * scale }]}>{BEIJING_TRIP_MOCK.day}</Text></View><View style={styles.next}><Text style={styles.nextLabel}>下一站</Text><Text style={styles.nextName}>{BEIJING_TRIP_MOCK.nextStop}</Text><Text style={styles.nextTime}>{BEIJING_TRIP_MOCK.departure}</Text></View><View style={styles.arrow}><Ionicons name="arrow-forward" size={16} color="#FFF" /></View></View>
    <View style={styles.stats}>{BEIJING_TRIP_MOCK.stats.map(stat => <View style={styles.stat} key={stat.label}><Ionicons name={stat.icon as any} size={17} color={colors.primary} /><Text style={styles.statLabel}>{stat.label}</Text><Text style={[styles.statValue, { fontSize: 13 * scale }]}>{stat.value}</Text></View>)}</View>
    <View style={styles.timeline}>{BEIJING_TRIP_MOCK.timeline.map((item, index) => <View style={styles.timelineRow} key={item.time}><View style={styles.lineCol}><View style={[styles.dot, index === 0 && styles.dotActive]} />{index < BEIJING_TRIP_MOCK.timeline.length - 1 && <View style={styles.line} />}</View><View style={styles.timelineCopy}><Text style={styles.timelineTime}>{item.time}</Text><Text style={styles.timelineTitle}>{item.title}</Text><Text style={styles.timelineDetail}>{item.detail}</Text></View></View>)}</View>
  </Pressable>;
}

const styles = StyleSheet.create({
  card: { backgroundColor: '#FFF', borderRadius: 24, padding: 18, shadowColor: '#0F2B27', shadowOffset: { width: 0, height: 12 }, shadowOpacity: 0.09, shadowRadius: 22, elevation: 4 }, pressed: { transform: [{ scale: 0.985 }] }, header: { flexDirection: 'row', alignItems: 'flex-start' }, kicker: { color: colors.primary, fontWeight: '800', letterSpacing: 1 }, day: { color: '#0F2B27', fontWeight: '900', marginTop: 4 }, next: { flex: 1, marginLeft: 18, paddingLeft: 14, borderLeftWidth: 1, borderLeftColor: '#E5EEEB' }, nextLabel: { color: '#82938F', fontSize: 10 }, nextName: { color: '#0F2B27', fontSize: 14, fontWeight: '800', marginTop: 3 }, nextTime: { color: '#C9853E', fontSize: 11, fontWeight: '700', marginTop: 3 }, arrow: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary }, stats: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 18, paddingTop: 14, borderTopWidth: 1, borderTopColor: '#EDF2F0', gap: 12 }, stat: { width: '45%', minHeight: 40 }, statLabel: { color: '#82938F', fontSize: 10, marginTop: 4 }, statValue: { color: '#304641', fontWeight: '800', marginTop: 2 }, timeline: { marginTop: 15, paddingTop: 14, borderTopWidth: 1, borderTopColor: '#EDF2F0' }, timelineRow: { flexDirection: 'row', minHeight: 54 }, lineCol: { width: 22, alignItems: 'center' }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#C8D6D2', marginTop: 4 }, dotActive: { width: 11, height: 11, borderRadius: 6, backgroundColor: colors.primary, borderWidth: 3, borderColor: '#C9F0E9' }, line: { flex: 1, width: 1, backgroundColor: '#DCE8E4', marginVertical: 3 }, timelineCopy: { flex: 1, marginLeft: 9 }, timelineTime: { color: colors.primary, fontSize: 10, fontWeight: '800' }, timelineTitle: { color: '#304641', fontSize: 12, fontWeight: '800', marginTop: 2 }, timelineDetail: { color: '#82938F', fontSize: 10, marginTop: 2 },
});
