import React, { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../../theme/colors';
import { ITINERARY_PREVIEW, PlannerCandidate } from '../../data/beijingHomeMock';

type Props = { visible: boolean; onClose: () => void; onCreate: () => Promise<void>; days: string; selectedCandidates?: PlannerCandidate[]; modeLabel?: string };

export default function ItineraryPreviewSheet({ visible, onClose, onCreate, days, selectedCandidates = [], modeLabel = 'AI行程' }: Props) {
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const dayCount = Number.parseInt(days, 10) || 4;
  const generatedDays = Array.from({ length: dayCount }, (_, index) => ITINERARY_PREVIEW[index % ITINERARY_PREVIEW.length]);
  const selectedNames = selectedCandidates.map(item => item.name);
  const create = async () => { if (creating) return; setCreating(true); setError(null); try { await onCreate(); } catch (e) { setError(e instanceof Error ? e.message : '创建行程失败，请稍后重试'); } finally { setCreating(false); } };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><Pressable style={styles.dismiss} onPress={onClose} /><View style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><View><Text style={styles.eyebrow}>AI TRIP PREVIEW · {modeLabel}</Text><Text style={styles.title}>北京 · {dayCount}天{dayCount - 1}晚</Text><Text style={styles.subtitle}>确认后会保存为正式行程</Text></View><Pressable onPress={onClose} hitSlop={12}><Ionicons name="close-circle-outline" size={25} color="#82938F" /></Pressable></View><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.list}>{selectedNames.length > 0 && <View style={styles.selectedSummary}><Text style={styles.selectedSummaryTitle}>本次已选择</Text><Text style={styles.selectedSummaryText}>{selectedNames.join(' · ')}</Text></View>}{generatedDays.map((day, index) => <View style={styles.day} key={`${day.day}-${index}`}><View style={styles.dayBadge}><Text style={styles.dayBadgeText}>DAY {index + 1}</Text></View><View style={styles.dayCopy}><Text style={styles.dayTitle}>{day.title}</Text>{day.items.map((item, itemIndex) => <Text style={styles.item} key={`${item}-${itemIndex}`}><Text style={styles.itemDot}>• </Text>{selectedNames.length > 0 ? selectedNames[(itemIndex + index) % selectedNames.length] : item}</Text>)}</View></View>)}</ScrollView>{error && <Text style={styles.error}>{error}</Text>}<Pressable onPress={() => void create()} disabled={creating} style={[styles.button, creating && styles.buttonDisabled]}><Text style={styles.buttonText}>{creating ? '正在创建…' : '创建并查看行程'}</Text>{!creating && <Ionicons name="arrow-forward" size={17} color="#FFF" />}</Pressable></View></View></Modal>;
}

const styles = StyleSheet.create({ overlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(6,32,28,0.35)' }, dismiss: { flex: 1 }, sheet: { maxHeight: '84%', backgroundColor: '#FFF', borderTopLeftRadius: 30, borderTopRightRadius: 30, padding: 22, paddingBottom: 30 }, handle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#CBD8D4', alignSelf: 'center', marginBottom: 20 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, eyebrow: { color: colors.primary, fontSize: 10, fontWeight: '900', letterSpacing: 1.4 }, title: { color: '#0F2B27', fontSize: 25, fontWeight: '900', marginTop: 5 }, subtitle: { color: '#71827F', fontSize: 12, marginTop: 4 }, list: { paddingVertical: 20, gap: 15 }, selectedSummary: { padding: 12, borderRadius: 14, backgroundColor: '#EFF9F5' }, selectedSummaryTitle: { color: colors.primaryDark, fontSize: 11, fontWeight: '900' }, selectedSummaryText: { color: '#60736E', fontSize: 11, lineHeight: 18, marginTop: 4 }, day: { flexDirection: 'row', gap: 14, padding: 15, borderRadius: 18, backgroundColor: '#F7FAF9' }, dayBadge: { width: 52, height: 49, borderRadius: 15, backgroundColor: '#DDF4EF', alignItems: 'center', justifyContent: 'center' }, dayBadgeText: { color: colors.primaryDark, fontSize: 10, fontWeight: '900' }, dayCopy: { flex: 1 }, dayTitle: { color: '#0F2B27', fontSize: 14, fontWeight: '800', marginBottom: 5 }, item: { color: '#60736E', fontSize: 12, lineHeight: 21 }, itemDot: { color: colors.primary, fontWeight: '900' }, button: { minHeight: 50, borderRadius: 25, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7 }, buttonText: { color: '#FFF', fontSize: 14, fontWeight: '800' }, error: { color: '#B54A3C', fontSize: 12, marginBottom: 10 }, buttonDisabled: { opacity: 0.7 } });
