import React from 'react';
import { Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../../theme/colors';
import { PARAMETER_OPTIONS, PlannerParams } from '../../data/beijingHomeMock';

type Key = keyof PlannerParams;
const LABELS: Record<Key, string> = { days: '旅行天数', people: '出行人数', budget: '预计预算', pace: '旅行节奏' };

export default function PlannerParameterPicker({ field, value, onClose, onChange }: { field: Key | null; value: PlannerParams; onClose: () => void; onChange: (field: Key, value: string) => void }) {
  const [customBudget, setCustomBudget] = React.useState(value.budget.replace(/[^0-9]/g, ''));
  React.useEffect(() => { if (field === 'budget' && value.budget !== '自定义') setCustomBudget(value.budget.replace(/[^0-9]/g, '')); }, [field, value.budget]);
  return <Modal visible={field !== null} transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.overlay} onPress={onClose}><Pressable style={styles.sheet} onPress={() => undefined}>
    <View style={styles.handle} />{field && <><View style={styles.header}><Text style={styles.title}>{LABELS[field]}</Text><Pressable onPress={onClose} hitSlop={12}><Ionicons name="close" size={22} color="#71827F" /></Pressable></View><View style={styles.options}>{PARAMETER_OPTIONS[field].map(option => { const active = value[field] === option; return <Pressable key={option} onPress={() => { if (option === '自定义') onChange(field, option); else { onChange(field, option); onClose(); } }} style={[styles.option, active && styles.optionActive]}><Text style={[styles.optionText, active && styles.optionTextActive]}>{option}</Text>{active && <Ionicons name="checkmark-circle" size={20} color={colors.primary} />}</Pressable>; })}</View>{field === 'budget' && value.budget === '自定义' && <View style={styles.customBox}><Text style={styles.customLabel}>输入本次预算（1000–50000）</Text><View style={styles.customRow}><Text style={styles.currency}>¥</Text><TextInput value={customBudget} onChangeText={text => setCustomBudget(text.replace(/[^0-9]/g, ''))} keyboardType="number-pad" placeholder="例如 6500" style={styles.customInput} /><Pressable disabled={Number(customBudget) < 1000 || Number(customBudget) > 50000} onPress={() => { onChange('budget', `¥${customBudget}`); onClose(); }} style={[styles.confirm, (Number(customBudget) < 1000 || Number(customBudget) > 50000) && styles.confirmDisabled]}><Text style={styles.confirmText}>确认</Text></Pressable></View></View>}</>}</Pressable></Pressable></Modal>;
}

const styles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(7,35,31,0.38)', justifyContent: 'flex-end' }, sheet: { backgroundColor: '#FFF', borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, paddingBottom: 34 }, handle: { width: 38, height: 4, borderRadius: 2, alignSelf: 'center', backgroundColor: '#CBD8D4', marginBottom: 18 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, title: { color: '#0F2B27', fontSize: 18, fontWeight: '800' }, options: { gap: 9, marginTop: 18 }, option: { minHeight: 52, borderRadius: 15, borderWidth: 1, borderColor: '#E3EBE8', paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, optionActive: { borderColor: colors.primary, backgroundColor: '#F1FBF9' }, optionText: { color: '#304641', fontSize: 14, fontWeight: '600' }, optionTextActive: { color: colors.primaryDark, fontWeight: '800' }, customBox: { marginTop: 14, padding: 12, borderRadius: 15, backgroundColor: '#F4FAF7' }, customLabel: { color: '#617571', fontSize: 11, fontWeight: '700' }, customRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 }, currency: { color: colors.primaryDark, fontSize: 18, fontWeight: '900' }, customInput: { flex: 1, height: 43, marginHorizontal: 7, paddingHorizontal: 10, borderRadius: 11, backgroundColor: '#FFF', color: '#0F2B27', fontSize: 16 }, confirm: { minHeight: 43, paddingHorizontal: 14, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primary }, confirmDisabled: { opacity: 0.4 }, confirmText: { color: '#FFF', fontSize: 12, fontWeight: '800' },
});
